---
server:
  port: 3306
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show_sql: false
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    